// example/vue-vite/src/components/Ready.vue
<script setup lang="ts">
import { ref } from 'vue';
import { mincu } from 'mincu-vanilla'

defineProps<{
  fallback: any
}>();

const ready = ref(mincu.isReady && mincu.isApp)

</script>

<template>
  <template v-if="ready">
    <slot></slot>
  </template>

  <template v-if="!ready">
    <component :is="fallback"></component>
  </template>
</template>

// packages/react/src/components/Ready.tsx
import React, { FC } from 'react'
import { useAppReady } from 'mincu-hooks'
import { Fallback } from './Fallback'

export interface Props {
  fallback?: React.ReactNode
  children?: React.ReactNode
}

export const Ready: FC<Props> = ({ fallback = (<Fallback />) as any, children }) => {
  const isReady = useAppReady()

  return isReady ? children : fallback
}
